# Numpy tutorial for Asia University

In [0]:
import numpy as np

## Numpy introduction
- 提供陣列array型態，可以做多維度的矩陣操作與運算
- 此資料格式為機器學習與深度學習模型一致可接受的格式
- Pandas dataframe的底層資料結構亦為np.array

---

# Create numpy array

In [2]:
x = np.array([1,2,3])
print(type(x))
print(x.dtype)
print(x)
print(x.shape)

<class 'numpy.ndarray'>
int64
[1 2 3]
(3,)


In [29]:
x = np.array([[1,2,3],[4,5,6]])
print(type(x))
print(x.dtype)
print(x)
print(x.shape)

<class 'numpy.ndarray'>
int64
[[1 2 3]
 [4 5 6]]
(2, 3)


#### np.zeros

In [4]:
zeros = np.zeros(4)
print(zeros)

[0. 0. 0. 0.]


#### np.ones

In [5]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


#### np.zeros_like

In [6]:
data_list = [1,2,3,4,5]

zeros_l = np.zeros_like(data_list)
print(zeros_l)

[0 0 0 0 0]


#### np.ones_like

In [7]:
data_list = ['a','b','c','d']

ones_l = np.ones_like(data_list)
print(ones_l)

['1' '1' '1' '1']


#### np.arange

In [8]:
arange = np.arange(15)
print(arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### np.empty

In [9]:
np.empty(10, dtype = int)

array([           72705008,                  54,          4294967295,
       7147042649926496103, 7451595014149599084, 3636198724363187569,
       7291168867612782639, 8028075837187318638, 7451599682962415470,
           122545876660270])

#### np.diag

In [10]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

print(np.diag(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [12]:
x = np.linspace(0, 20, 10)
x

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

---

# Random module

In [13]:
x = np.random.rand(2,3)
print(x)

[[0.44162862 0.73105496 0.21048761]
 [0.47970287 0.63768658 0.17085655]]


In [14]:
x = np.random.random(5)
print(x)

[0.17174804 0.78285748 0.37892131 0.83977622 0.50790846]


In [15]:
x = np.random.randint(0, 10, size = 5)
print(x)

[7 9 7 1 2]


---

# Reshape

In [16]:
x = np.array([1,2,3,4,5,6])

print(x.shape)

(6,)


In [17]:
print(x.reshape(1,6).shape)
print(x.reshape(2,3).shape)
print(x.reshape(2,3,1).shape)
print(x.reshape(3,-1).shape)

(1, 6)
(2, 3)
(2, 3, 1)
(3, 2)


---

# Element-wise / Matrix operations

In [18]:
x = np.arange(12).reshape(3,4)
y = np.arange(12).reshape(3,4)+1

print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## add

In [19]:
x + y

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [20]:
np.add(x,y)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

## subtract

In [21]:
x-y

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [22]:
np.subtract(x,y)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

## multiply

In [23]:
x * y

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [24]:
np.multiply(x, y)

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

## divide

In [25]:
x / y

array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286, 0.875     ],
       [0.88888889, 0.9       , 0.90909091, 0.91666667]])

In [26]:
np.divide(x, y)

array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286, 0.875     ],
       [0.88888889, 0.9       , 0.90909091, 0.91666667]])

## dot

In [27]:
x @ y.transpose()

array([[ 20,  44,  68],
       [ 60, 148, 236],
       [100, 252, 404]])

In [28]:
np.dot(x, y)

ValueError: ignored

In [0]:
np.dot(x, y.transpose())

In [0]:
np.matmul(x,y.transpose())

## outer

In [0]:
np.outer(x, y)

---

# Statistics and Math

In [0]:
x = np.arange(12).reshape(3,4)
x

## max

In [0]:
np.max(x)

In [0]:
np.max(x, axis = 0)

## min

In [0]:
np.min(x)

In [0]:
np.min(x, axis = 1)

## mean

In [0]:
np.mean(x)

In [0]:
np.mean(x, axis = 0)

## correlation

In [0]:
x = np.random.randn(50).reshape(5,10)

np.corrcoef(x) #注意，這邊是針對row做correlation (把row看成一個欄位資料而非觀察值)

## log

In [0]:
np.log(3)

In [0]:
np.log10(3)

## exp

In [0]:
np.exp([1,2,3])

## cos

In [0]:
np.cos([1,2,3])

## sin

In [0]:
np.sin([1,2,3])

---

# Manipulation

## slicing

In [0]:
x = np.arange(12).reshape(3,4)
x

In [0]:
x[0]

In [0]:
x[1,0:2]

In [0]:
x[1:2,0:2]

In [0]:
x[:,1]

In [0]:
x[:,::-1]

## set value

In [0]:
x = np.arange(12).reshape(3,4)
x

In [0]:
x[0:1,:] = -100
x

## boolean operation / isin / isnan / equal

In [0]:
x = np.array([1, np.nan, 2, 3])

In [0]:
x>1

In [0]:
np.isin(x, [1,3]) #not in的意思

In [0]:
np.isnan(x)

In [0]:
y = np.arange(4)
print(y)

np.equal(x, y)

## concatenation

In [0]:
x = np.arange(12, dtype = 'float').reshape(4,3)
y = np.random.randn(12).reshape(4,3)

print(x)
print(y)

### concatenate by row

In [0]:
z = np.concatenate((x, y), axis = 0)
print(z)
print(z.shape)

In [0]:
z = np.vstack((x, y))
print(z)
print(z.shape)

### concatenate by column

In [0]:
z = np.concatenate((x, y), axis = 1)
print(z)
print(z.shape)

In [0]:
z = np.hstack((x, y))
print(z)
print(z.shape)